services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - pdf_extract_network

volumes:
  ollama_data:

networks:
  pdf_extract_network:
    name: pdf_extract_network
